enum BARCODE_TYPE {
    NONE = 'NONE',
    CODA_BAR = 'CODABAR',
    CODE_39 = 'CODE39',
    CODE_93 = 'CODE93',
    CODE_128 = 'CODE128',
    DATA_MATRIX = 'DATAMATRIX',
    EAN_8 = 'EAN8',
    EAN_13 = 'EAN13',
    ITF = 'ITF',
    MAXI_CODE = 'MAXICODE',
    PDF_417 = 'PDF417',
    RSS_14 = 'RSS14',
    RSS_EXPANDED = 'RSSEXPANDED',
    UPC_A = 'UPCA',
    UPC_E = 'UPCE',
    UPC_EAN_EXTENSION = 'UPCEANEXTENSION'
};

export default BARCODE_TYPE;