#Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.0.20
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pa22word@!
      MONGO_INITDB_DATABASE: demo
    ports:
      - '27017:27017'
    command: [--auth]
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pa22word@!